### ISSUE TITLE
Docker Image on Dockerhub or ghcr?

### ISSUE THREAD

**Issue by Gandalf-the-Blue** [ahobsonsayers/abs-tract#10]
Hi,

Is it possible for you to publish the docker image on either dockerhub or ghcr?
I did find one image on [dockerhub](https://hub.docker.com/r/arranhs/abs-tract), but given the different names wanted to confirm, if this is legit?

**Comment by ahobsonsayers** [comment]
Hi! abs-tract is indeed already published on dockerhub at the link you posted. I am unsure as what you mean by different names though? Do you mean my username?

There is an example docker run command in the readme that shows how to pull and use the correct image from Dockerhub. Alternatively, you can look at the docker compose. Hope this helps!
