### ISSUE TITLE
Investigate why Goodreads sometimes finds no matches

### ISSUE THREAD

**Issue by ahobsonsayers** [ahobsonsayers/abs-tract#8]
I have identified several books that when searched with Goodreads by title and author, no matches are found. We should investigate why.

Examples:

- "Mike at Wrykyn" by P.G. Wodehouse
- "Dr. No" by Ian Fleming
- "The Atlantis Complex" by Eoin Colfer
- "Artemis Fowl and the Last Guardian" by Eoin Colfer (This does find a match with just "The Last Guardian" as the title, but we should find a match with the title specified)

I suspect this is to do with the fuzzy matching we do when getting author books. We could possibly strip special characters, and also check exact matches of contains (if fuzzy matching doesnt match these)

**Comment by yetti7** [comment]
Just wanted to comment since you dont have a discussion area on here. Thanks for the work you've put in! This has made life a few steps easier! Looking forward to the next release!

**Comment by ahobsonsayers** [comment]
Completes in release https://github.com/ahobsonsayers/abs-tract/releases/tag/v0.2.0
